### ISSUE TITLE
Gohan ignores loading schema when it contains property with relation to itself

### ISSUE THREAD

**Issue by marcin-ptaszynski** [cloudwan/gohan#177]
In case when schema defines property with relation to itself, like:
``` yaml
- id: person
...
  properties:
    id:
      description: The ID of the Virtual Machine.
      permission:
      - create
      title: ID
      type: string
      unique: true
    parent:
      description: ""
      permission:
      - create
      relation: person
      title: Parent
      type: string
```

We get a Warning:
```
10:30:57.504 gohan.schema WARNING  Error in reordering schema Schemas aren't DAG. We can't reorder automatically
```

This results in schema not being created in database and server running without any CRITICAL Error.

I Think there are actually two issues here:

1. Relationship to itself should not be considered a cycle for Gohan
2. Not being able to register schema should result in critical error
