### ISSUE TITLE
Aliase for parent->child relationships

### ISSUE THREAD

**Issue by yudai** [cloudwan/gohan#203]
Hi, I'm wondering if there is a way to define aliases to resource names when they have parents.

Let's say, we have "events" on the resource type "network" and "subnet". We will have the schemas like below, because we cannot define the common "event" resource type that is a child of both "network" and "subnet"

```yaml
schemas:
- id: network
  ...
- id: network_event
  parent: network
  ...
- id: subnet
  ...
- id: subnet_event
  parent: subnet
  ...
```

In this case, the URL for events of networks will look like: `http://gohan/networks/<id>/network_events` and events of subnets will be `http://gohan/subnets/<id>/subnet_events`. These URLs are bit redundant.
If we could have an alias like `http://gohan/networks/<id>/events` and `http://gohan/subnets/<id>/events`, the URLs will be more clean and shorter.

I think that the same thing can happen in many cases so I'd like to have some discussion on this issue.
