### ISSUE TITLE
Resource cannot have two relations to the same resource if it has another relational resource

### ISSUE THREAD

**Issue by morrisson** [cloudwan/gohan#215]
Example schema:
```
schemas:

- id: gakko
  description: Gakko
  singular: gakko
  plural: gakkos
  title: Gakko
  prefix: /v1.0
  schema:
    properties:
      id:
        description: The ID of Gakko
        format: uuid
        title: ID
        type: string
      name:
        description: Name
        title: Name
        type: string

- id: kodomo
  description: Kodomo
  singular: kodomo
  plural: kodomos
  title: Kodomo
  prefix: /v1.0
  schema:
    properties:
      id:
        description: The ID of Kodomo
        format: uuid
        title: ID
        type: string
      gakko_id:
        description: Gakko
        title: Gakko
        type: string
        relation: gakko
        relation_property: gakko

- id: oya
  description: Oya
  singular: oya
  plural: oyas
  title: Oya
  prefix: /v1.0
  schema:
    properties:
      id:
        description: The ID of Oya
        format: uuid
        title: ID
        type: string
      otoko_id:
        description: Otoko no ko
        title: Otoko
        type: string
        relation: kodomo
        relation_property: otoko_kodomo
      onna_id:
        description: Onna no ko
        title: Onna
        type: string
        relation: kodomo
        relation_property: onna_kodomo
```

Example initial values.
```
gakkos:
- id: gakko1
  name: Gakko 1
kodomos:
- id: otoko_id
  gakko_id: gakko1
- id: onna_id
  gakko_id: gakko1
oyas:
- id: oya_id
  otoko_id: otoko_id
  onna_id: onna_id
```

In this setting, if you want to get the list of oyas like `curl http://localhost:9091/v1.0/oyas`, following errors show:
```
18:13:49.638 gohan.db.sql DEBUG  Executing SQL query 'SELECT oyas.`id` as `oyas__id`, oyas.`otoko_id` as `oyas__otoko_id`, otoko_kodomo.`id` as `otoko_kodomo__id`, otoko_kodomo.`gakko_id` as `otoko_kodomo__gakko_id`, gakko.`id` as `gakko__id`, gakko.`name` as `gakko__name`, oyas.`onna_id` as `oyas__onna_id`, onna_kodomo.`id` as `onna_kodomo__id`, onna_kodomo.`gakko_id` as `onna_kodomo__gakko_id`, gakko.`id` as `gakko__id`, gakko.`name` as `gakko__name` FROM `oyas` LEFT JOIN `kodomos` as `otoko_kodomo` on `oyas`.`otoko_id` = `otoko_kodomo`.id LEFT JOIN `gakkos` as `gakko` on `otoko_kodomo`.`gakko_id` = `gakko`.id LEFT JOIN `kodomos` as `onna_kodomo` on `oyas`.`onna_id` = `onna_kodomo`.id LEFT JOIN `gakkos` as `gakko` on `onna_kodomo`.`gakko_id` = `gakko`.id ORDER BY oyas.`id` asc'
18:13:49.638 gohan.server.middleware ERROR  Error 1066: Not unique table/alias: 'gakko'
```

The root cause is gohan produced two same 'gakko' aliases.
