### ISSUE TITLE
Policy condition doesn't support OR expressions

### ISSUE THREAD

**Issue by marcin-ptaszynski** [cloudwan/gohan#323]
Policy condition allows to define property, is_owner

```
      - action: 'update'
        condition:
        - type: is_owner
        - type: property
          match:
            status:
              - ACTIVE
              - CREATE_IN_PROGRESS
              - UPDATE_IN_PROGRESS
              - DELETE_IN_PROGRESS
              - ERROR
        effect: allow
        id: member
        principal: Member
```
which will apply AND rule. Unfortunately, there is no way to implement "shared admin resource", which can be created by normal user within his project, but admin can also create and then publish it for all tenants with "is_public" flag.

Policy could look like this:
```
      - action: 'read'
        condition:
        - type: or
          operands:
          - type: is_owner
          - type: property
            match:
              is_public: true
        effect: allow
        id: member
        principal: Member
```

Note:
Policy itself should be simple, but the bigger problem is db layer, which doesn't allow for OR operators (only AND, =, WHERE IN).
