### ISSUE TITLE
FSM Support

### ISSUE THREAD

**Issue by nati** [cloudwan/gohan#6]
Finite state machine is a one of generic pattern in resource management application.
We would like to support this as a kind of metaschema.
state management schema can be used to generate doc & UI & assert illegal update.

This enforcement will be applied on model layer so we can apply this enforcement in cascading model update.

``` yaml
state_management:
 schemas: # list of schema ID
 - $SCHEMA_1
 - $SCHEMA_2
 property_id:  $STATUS # status property
 states:
   $STATUS_NAME: # 
      $ACTION: # allowed action on this status  ( create / update / delete )
          - $NEXT_STATUS1  # list of allowed next status
          - $NEXT_STATUS2
```

Note a special state "NONE" means it isn't exist in DB.

Example
We can have state_machine in property

``` yaml

 states_machine:
  NONE:
    create:
    - CREATE_IN_PROGRESS
    - ERROR
  ACTIVE:
    update:
    - REBOOTING:
    - UPDATE_IN_PROGERSS
    - ERROR
    delete:
    - DELETE_IN_PROGRESS
    - ERROR
  CREATE_IN_PROGRESS:
    update:
    - ACTIVE
    - ERROR
  UPDATE_IN_PROGRESS:
    update:
    - ACTIVE
    - ERROR
  DELETE_IN_PROGRESS:
    delete:
    - NONE
  REBOOTING:
    update:
    - ACTIVE
    - ERROR
  ERROR:
    delete:
    - DELETE_IN_PROGRESS
    - ERROR
    - FATAL_ERROR
    update:
    - UPDATE_IN_PROGRESS
```

References:
- FSM https://en.wikipedia.org/wiki/Finite-state_machine
