### ISSUE TITLE
Schema inheritance

### ISSUE THREAD

**Issue by nati** [cloudwan/gohan#7]
Allow inherit schema in order to write JSON schema efficiently.

``` yaml
schemas:
  - id: base
    type: abstract
    schema:
   ...

- schemas
  - id: network
  - extends:  # list of abstract schemas
     -
     - 
```

When we found this, we will do this when we load schemas.

- merge properties
- append propertiesOrder in the order of with
